ALTER TABLE "users" ADD COLUMN "hasVolcengineCredentials" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "hasGptApiKey" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "hasGeminiApiKey" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "hasArkApiKey" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN "hasSuperbedToken" BOOLEAN NOT NULL DEFAULT false;
